import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Earth Store",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <section className="">
        {/* Hero section */}

        <div className="flex h-[80dvh] flex-col items-center gap-3 bg-[url('/home-images/banner.jpg')] bg-cover bg-center bg-no-repeat">
          <div className="text-color-seaweed pt-[10rem] text-5xl font-bold tracking-[.5rem]">
            EARTH
          </div>
          <div className="dark:text-background text-2xl font-light tracking-widest">
            ENDLESS POTENTIAL
          </div>
          <Button className="bg-color-chelsea-cucumber hover:bg-color-seaweed mt-2 rounded-none px-7 py-3.5 dark:text-white">
            EXPLORE
          </Button>
        </div>

        {/* Services section */}

        <div className="mx-auto space-y-10 px-6 py-16">
          <div className="">
            <Image
              src={"/home-images/web-design.jpg"}
              alt="Web Design"
              width={348}
              height={275}
            />
            <div className="pt-4 text-2xl font-bold">Web Design</div>
            <div className="text-foreground/50 pt-2">
              Custom web design for small businesses, we help you capture new
              audiences and increase your sales.
            </div>
          </div>

          <div className="">
            <Image
              src={"/home-images/graphic-Design.jpg"}
              alt="Graphic Design"
              width={348}
              height={275}
            />
            <div className="pt-4 text-2xl font-bold">Graphic Design</div>
            <div className="text-foreground/50 pt-2">
              Logos, merchandise and more. Anyone can create nice graphics. We
              think it’s better to create memorable ones.
            </div>
          </div>

          <div className="">
            <Image
              src={"/home-images/content-Writing.jpg"}
              alt="Content Creation"
              width={348}
              height={275}
            />
            <div className="pt-4 text-2xl font-bold">Content Creation</div>
            <div className="text-foreground/50 pt-2">
              Want to attract people to your website? You have to have the best
              content in the world. That’s what we do.
            </div>
          </div>
        </div>

        {/* About section */}

        <div className="mx-auto space-y-4 px-6 py-16">
          <div className="text-3xl font-bold tracking-widest">ABOUT US</div>
          <div className="">
            I made it so it is super easy to update and so that it flows
            perfectly with my tutorials. Lots of love and hundreds of hours went
            into making it. I hope you love it as much as I do. I wish you the
            best of luck with your business, enjoy the adventure.
          </div>
          <Image
            src={"/home-images/our-mission-min.jpg"}
            alt="About Us"
            width={348}
            height={275}
          />
        </div>

        {/* Contact section */}
        <div className="flex h-[70dvh] flex-col items-center justify-center gap-3 bg-[url('/home-images/call-to-action.jpg')] bg-cover bg-center bg-no-repeat px-6">
          <div className="text-color-seaweed text-center text-4xl font-bold tracking-wider">
            TALK TO US
          </div>
          <div className="dark:text-background text-center">
            Have any questions? We are always open to talk about your business,
            new projects, creative opportunities and how we can help you.
          </div>
          <Button className="bg-color-chelsea-cucumber hover:bg-color-seaweed mt-6 rounded-none px-8 py-6 tracking-widest dark:text-white">
            GET IN TOUCH
          </Button>
        </div>
      </section>
    </>
  );
};

export default page;
